name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      
      - name: Install Vyper
        run: pip install vyper==0.4.1
      

      - name: Install Mamushi
        run: pip install mamushi==0.0.4

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
      
      - name: 'Create env file'
        run: |
          touch .env
          echo MAINNET_RPC_URL=${{ secrets.MAINNET_RPC_URL }} >> .env

      - name: Show Forge version
        run: |
          forge --version

      - name: Run Forge fmt
        run: |
          forge fmt --check
        id: fmt
      

      - name: Run Mamushi
        run: |
          mamushi --check
        id: mamushi

      - name: Run Forge build
        run: |
          forge build --sizes
        id: build

      - name: Run Forge tests
        run: |
          forge test -vvv
        id: test
